// Package inspect reads bounded metadata and explicitly requested lookups from
// stategeodb-generated MMDB artifacts.
package inspect

import (
	"context"
	"errors"
	"fmt"
	"net/netip"
	"os"
	"syscall"

	maxminddb "github.com/oschwald/maxminddb-golang/v2"

	"github.com/vikewoods/stategeodb/internal/mmdb"
	"github.com/vikewoods/stategeodb/internal/source"
)

const maxAddresses = 32

var (
	// ErrInvalidRequest classifies invalid database paths or address lists.
	ErrInvalidRequest = errors.New("inspect: invalid request")
	// ErrOpen classifies filesystem failures opening an artifact.
	ErrOpen = errors.New("inspect: open failure")
	// ErrUnsupported classifies valid MMDBs not generated by stategeodb with
	// the supported schema and encoding contract.
	ErrUnsupported = errors.New("inspect: unsupported database")
	// ErrCorrupt classifies malformed artifacts or structural verification failures.
	ErrCorrupt = errors.New("inspect: corrupt database")
	// ErrLookup classifies lookup, decoding, or normalized-value failures.
	ErrLookup = errors.New("inspect: lookup failure")
	// ErrClose classifies failures releasing the opened database.
	ErrClose = errors.New("inspect: close failure")
)

// Request identifies one generated artifact and at most 32 explicit addresses.
type Request struct {
	DatabasePath string
	Addresses    []netip.Addr
}

// Metadata is the bounded generated-artifact metadata returned by Inspect.
type Metadata struct {
	DatabaseType      string
	SchemaVersion     int
	BuildEpoch        uint
	BinaryFormatMajor uint
	BinaryFormatMinor uint
	IPVersion         uint
	RecordSize        uint
	NodeCount         uint
}

// Lookup is one explicit address result. Found distinguishes an absent prefix
// from a data-bearing prefix whose normalized location is unknown.
type Lookup struct {
	Address     netip.Addr
	Found       bool
	Prefix      netip.Prefix
	Country     string
	Subdivision string
}

// Result contains fixed metadata and caller-owned lookup storage.
type Result struct {
	Metadata Metadata
	Lookups  []Lookup
}

// Inspect opens, verifies, and directly looks up a bounded set of addresses.
// The upstream Verify and individual Lookup calls are synchronous and cannot
// be interrupted within one call; cancellation is checked at every boundary.
func Inspect(ctx context.Context, request Request) (Result, error) {
	return inspect(ctx, request, defaultOperations())
}

type database interface {
	Metadata() maxminddb.Metadata
	Verify() error
	Lookup(netip.Addr) lookupResult
	Close() error
}

type lookupResult interface {
	Err() error
	Found() bool
	Prefix() netip.Prefix
	DecodePath(any, ...any) error
}

type operations struct {
	open func(string) (database, error)
}

type upstreamDatabase struct {
	reader *maxminddb.Reader
}

func defaultOperations() operations {
	return operations{
		open: func(path string) (database, error) {
			reader, err := maxminddb.Open(path)
			if err != nil {
				return nil, err
			}
			return upstreamDatabase{reader: reader}, nil
		},
	}
}

func (database upstreamDatabase) Metadata() maxminddb.Metadata {
	return database.reader.Metadata
}

func (database upstreamDatabase) Verify() error {
	return database.reader.Verify()
}

func (database upstreamDatabase) Lookup(address netip.Addr) lookupResult {
	return database.reader.Lookup(address)
}

func (database upstreamDatabase) Close() error {
	return database.reader.Close()
}

func inspect(ctx context.Context, request Request, operations operations) (Result, error) {
	normalized, err := validateRequest(ctx, request)
	if err != nil {
		return Result{}, err
	}
	if err := contextFailure(ctx, "open database"); err != nil {
		return Result{}, err
	}

	database, err := operations.open(normalized.DatabasePath)
	if err != nil {
		var openErr error
		if isFilesystemError(err) {
			openErr = classified("open database", ErrOpen)
		} else {
			openErr = classified("parse database", ErrCorrupt)
		}
		if cancelErr := contextFailure(ctx, "open database"); cancelErr != nil {
			openErr = errors.Join(openErr, cancelErr)
		}
		return Result{}, openErr
	}

	result, primary := inspectOpenDatabase(ctx, normalized, database)
	if closeErr := database.Close(); closeErr != nil {
		primary = errors.Join(primary, classified("close database", ErrClose))
	}
	if cancelErr := contextFailure(ctx, "return result"); cancelErr != nil {
		primary = errors.Join(primary, cancelErr)
	}
	if primary != nil {
		return Result{}, primary
	}
	return result, nil
}

func validateRequest(ctx context.Context, request Request) (Request, error) {
	if ctx == nil || request.DatabasePath == "" || len(request.Addresses) > maxAddresses {
		return Request{}, classified("validate request", ErrInvalidRequest)
	}

	normalized := Request{
		DatabasePath: request.DatabasePath,
		Addresses:    make([]netip.Addr, len(request.Addresses)),
	}
	for index, address := range request.Addresses {
		if !address.IsValid() || address.Zone() != "" {
			return Request{}, classified("validate address", ErrInvalidRequest)
		}
		normalized.Addresses[index] = address.Unmap()
	}
	return normalized, nil
}

func inspectOpenDatabase(ctx context.Context, request Request, database database) (Result, error) {
	metadata := database.Metadata()
	if !supportedMetadata(metadata) {
		return Result{}, classified("validate metadata", ErrUnsupported)
	}
	if err := contextFailure(ctx, "verify database"); err != nil {
		return Result{}, err
	}
	if err := database.Verify(); err != nil {
		return Result{}, classified("verify database", ErrCorrupt)
	}
	if err := contextFailure(ctx, "verify database"); err != nil {
		return Result{}, err
	}

	result := Result{
		Metadata: metadataResult(metadata),
		Lookups:  make([]Lookup, 0, len(request.Addresses)),
	}
	for _, address := range request.Addresses {
		if err := contextFailure(ctx, "lookup address"); err != nil {
			return Result{}, err
		}
		lookup, err := inspectLookup(database.Lookup(address), address)
		if err != nil {
			return Result{}, err
		}
		if err := contextFailure(ctx, "lookup address"); err != nil {
			return Result{}, err
		}
		result.Lookups = append(result.Lookups, lookup)
	}
	return result, nil
}

func supportedMetadata(metadata maxminddb.Metadata) bool {
	return metadata.DatabaseType == mmdb.DatabaseType &&
		len(metadata.Description) == 1 &&
		metadata.Description["en"] == mmdb.SchemaDescription &&
		len(metadata.Languages) == 0 &&
		metadata.BuildEpoch > 0 &&
		metadata.BinaryFormatMajorVersion == 2 &&
		metadata.BinaryFormatMinorVersion == 0 &&
		metadata.IPVersion == 6 &&
		metadata.RecordSize == 28 &&
		metadata.NodeCount > 0
}

func metadataResult(metadata maxminddb.Metadata) Metadata {
	return Metadata{
		DatabaseType:      metadata.DatabaseType,
		SchemaVersion:     mmdb.SchemaVersion,
		BuildEpoch:        metadata.BuildEpoch,
		BinaryFormatMajor: metadata.BinaryFormatMajorVersion,
		BinaryFormatMinor: metadata.BinaryFormatMinorVersion,
		IPVersion:         metadata.IPVersion,
		RecordSize:        metadata.RecordSize,
		NodeCount:         metadata.NodeCount,
	}
}

func inspectLookup(result lookupResult, address netip.Addr) (Lookup, error) {
	if err := result.Err(); err != nil {
		return Lookup{}, classified("lookup address", ErrLookup)
	}
	if !result.Found() {
		return Lookup{Address: address}, nil
	}

	prefix, err := source.NormalizePrefix(result.Prefix())
	if err != nil || !prefix.Contains(address) {
		causes := []error{ErrLookup}
		if err != nil {
			causes = append(causes, err)
		}
		return Lookup{}, classified("validate lookup prefix", causes...)
	}

	var country *string
	if err := result.DecodePath(&country, "country", "iso_code"); err != nil {
		return Lookup{}, classified("decode lookup country", ErrLookup)
	}
	var subdivision *string
	if err := result.DecodePath(&subdivision, "subdivisions", 0, "iso_code"); err != nil {
		return Lookup{}, classified("decode lookup subdivision", ErrLookup)
	}

	countryValue := ""
	if country != nil {
		countryValue = *country
	}
	subdivisionValue := ""
	if subdivision != nil {
		subdivisionValue = *subdivision
	}
	normalizedCountry, normalizedSubdivision, err := source.NormalizeLocation(
		countryValue,
		subdivisionValue,
	)
	if err != nil {
		return Lookup{}, classified("validate lookup location", ErrLookup, err)
	}
	return Lookup{
		Address:     address,
		Found:       true,
		Prefix:      prefix,
		Country:     normalizedCountry,
		Subdivision: normalizedSubdivision,
	}, nil
}

func contextFailure(ctx context.Context, operation string) error {
	if err := ctx.Err(); err != nil {
		return classified(operation, err)
	}
	return nil
}

func isFilesystemError(err error) bool {
	var pathError *os.PathError
	var syscallError *os.SyscallError
	var errno syscall.Errno
	return errors.As(err, &pathError) || errors.As(err, &syscallError) || errors.As(err, &errno)
}

func classified(operation string, causes ...error) error {
	return &classifiedError{operation: operation, causes: causes}
}

type classifiedError struct {
	operation string
	causes    []error
}

func (err *classifiedError) Error() string {
	return fmt.Sprintf("inspect %s: %v", err.operation, err.causes[0])
}

func (err *classifiedError) Unwrap() []error {
	return err.causes
}
